pipelines:
  custom:
    deploy_firebase_version:
      - step:
          runs-on:
            - self.hosted
            - macos
          script:
            - xcodebuild -workspace "Zap Comics.xcodeproj" -scheme "Zap Comics" -archivePath build/version/app.xcarchive archive
            - xcodebuild -exportArchive -archivePath build/version/app.xcarchive -exportPath build/version -exportOptionsPlist ci/profile/export.plist
            - firebase appdistribution:distribute IPA-PATH --app 1:787039729981:ios:48e1949daa9ed79fef2d54 --release-notes-file ci/releasenote.txt --groups-file ci/groups.txt  --testers-file ci/testers.txt --token 1//04IePVb53m-fJCgYIARAAGAQSNwF-L9IrMN_5gnKaSK0bF2P2g-npY8lpg4RkF4gJ7xhzOByTz4mq05H9oHG4WeEN1Iwi5fJb0QU